spring:
  cache:
    cache-names: demo,org.springframework.cloud.stream.schema.reflectionCache,org.springframework.cloud.stream.schema.referenceCache
    caffeine:
      spec: expireAfterWrite=10m
  cloud:
    stream:
      bindings:
        input:
          destination: testInput
          group: redis
        output:
          destination: testOutput
      default:
        content-type: application/*+avro
        group: redis
        required-groups: redis
      schema:
        avro:
          schema-locations:
            - classpath:avro/generated/Demo.avsc
      schema-registry-client:
        endpoint: http://localhost:51546

server:
  port: 0
